# 1. Files excluded from Jekyll builds
# 2. Plugins
# 3. Jekyll/Gem settings
# 4. Collections
# 5. Scholar

# 1. Files excluded from Jekyll builds
exclude:
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- jekyll-theme-ADA.gemspec
- .jekyll-cache

# 2. Plugins
gems:
#  - jekyll/scholar
  - jekyll-email-protect

# 3. Jekyll settings
paginate: 1
paginate_path: "/blog/page:num/"

author: Jakob Bossek
email: "bossek@aim.rwth-aachen.de"
encoding: utf-8
lang: en-GB
# activate to have a "text logo"
title: "ADA theme" # site name or title
#logo: "/assets/images/RWTH_logo.png" # relative path to logo
#logo_alt_text: "ADA theme logo"
# activate exclusively (comment 'title') to have a "text logo"
logo_text: "ADA"
description: "ADA website" # site description / default description
theme: jekyll-theme-ada
repo: "https://github.com/jakobbossek/jekyll-theme-ada"

defaults:
  - scope:
      path: ""
      type: "collaborators"
    values:
      layout: "collaborator"
  - scope:
      path: ""
    values:
      layout: "default"

# 4. Collections
collections:
  members:
    sort_by: order
  collaborators:
    sort_by: order
    output: true

# 5. Scholar
scholar:
  style: assets/bibliography/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending
  #bibliography_list_tag: ul

  source: _bibliography
  # repository: pdf
  bibliography: bib
  bibliography_template: bibentry

  replace_strings: true

  #details_dir:    bibliography
  #details_layout: bibtex.html
  #details_link:   Details

  query: "@*"
